#define DFU_STR_MANUF "Windfisch"
#define DFU_STR_PRODUCT "Midikraken bootloader"
#define DFU_CIPHER _DISABLE
#define DFU_SEAL_LEVEL 0
#define DFU_APP_START 0x2000
#define DFU_BOOTKEY_ADDR 0x20003000
#define DFU_DBLRESET_MS _DISABLE
#define DFU_BOOTSTRAP_GPIO GPIOB
#define DFU_BOOTSTRAP_PIN 12
#define DFU_VENDOR_ID 0x1209
#define DFU_DEVICE_ID 0x2E7F
