[package]
name = "midikraken"
version = "0.1.0"
authors = ["Florian Jung <flo@windfis.ch>"]
edition = "2018"

[features]
benchmark = []
debugprint = []

[dependencies]
cortex-m = "0.6.7"
cortex-m-rt = ">=0.6"
cortex-m-rtic = ">=0.5"
stm32f1xx-hal = { features = ["rt", "stm32f103", "stm32-usbd", "medium"] }
heapless = "0.6"
parse_midi = { path = "../lib/parse_midi" }
generic-array = "0.14"

usb-device = { version = ">=0.2.1", features = ["control-buffer-512"] }
usbd-midi = { path="../lib/usbd-midi" }
embedded-hal = ">=0.2.3"

[build-dependencies]
vergen = "3"

[patch.crates-io]
stm32f1xx-hal = { git = "https://github.com/Windfisch/stm32f1xx-hal", branch="timer_additions" }
usb-device = { git = "https://github.com/Windfisch/usb-device", branch = "merged" }

[profile.dev]
opt-level = "z"
debug = true
lto = true
[profile.release]
opt-level = 3
codegen-units = 1
debug = true
lto = true
