name: build

env:
  CARGO_TERM_COLOR: always

on: [push, pull_request]

jobs:
  rust:
    name: Compile firmware
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - nightly
          - nightly-2021-10-03
    steps:
      - run: sudo apt-get install binutils-arm-none-eabi
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          target: thumbv7m-none-eabi
      - run: make release.dfu.bin
        working-directory: firmware
      - run: make release.bare.bin
        working-directory: firmware
      - name: Upload binary_size to seriesci
        env:
          SERIESCI_TOKEN: ${{ secrets.SERIESCI_TOKEN }}
          TOOLCHAIN: ${{ matrix.rust }}
        run: |
          if [ $TOOLCHAIN == nightly-2021-10-03 ]; then
            curl --insecure --header "Authorization: Token $SERIESCI_TOKEN" --header "Content-Type: application/json" --data "{\"value\":\"$(stat --format %s firmware/release.dfu.bin) bytes\",\"sha\":\"${GITHUB_SHA}\"}" https://seriesci.com/api/Windfisch/midikraken/binary_size/one
          fi
